module.exports = {
    //Required by axios plugin in pages/_lang.vue to be able to load
    //data files required to render the page in a server including generation process.
    "hostName": "http://localhost:3000",
    //validLanguages is used in validate() method in application to determin if 
    //url parameter is a valid language, and if not - throw a not found page.
    //Without checking validity of language parameter error gets generated by VUE.
    //So this approach is looking much better.
    //     used in pages/_lang.vue
    "validLanguages": [
        "en-US",
        "lt",
        "de",
        "es",
        "pt",
        "fr",
        "ru"
    ]
}